export const ADD_TODO = "ADD TODO";
export const COMPLETE_TODO = "COMPLETE TODO";
export const CLEAR_ALL = "CLEAR ALL";
export const CLEAR_COMPLETED = "CLEAR COMPLETED";
export const CLEAR_SINGLE_TODO = "CLEAR SINGLE TODO"
